const INFURA_API_KEY = process.env.REACT_APP_INFURA_API_KEY
const MAINNET_ENS_REVERSE_RECORDS = '0x3671aE578E63FdF66ad4F3E12CC0c0d71Ac7510C'
const ENS_REVERSE_RECORDS_BATCH_SIZE = 300
const ENS_RESOLVE_BATCH_SIZE = 6

export {
  INFURA_API_KEY,
  MAINNET_ENS_REVERSE_RECORDS,
  ENS_REVERSE_RECORDS_BATCH_SIZE,
  ENS_RESOLVE_BATCH_SIZE,
}
